### PR TITLE
Add RSA key formatting, SHA-512 signing and verification, and fix RSA encryption/decryption

### PR DESCRIPTION
**Pull request by provokateurin**
Sorry that this is only a single commit/PR, but I was working on my app and had to add all of this to get it working.

### CODE REVIEW

**Comment by provokateurin** [comment]
Had to rebase. I will update the comments for signing later

**Comment by konstantinullrich** [comment]
Before I merge, can you please please check what went wrong in the failed Test?

**Comment by provokateurin** [comment]
@konstantinullrich everything fixed and finished.

**Comment by konstantinullrich** [comment]
Thanks, i'll review the code and then merge your request

**Review by konstantinullrich — APPROVED** [review]

**Comment by provokateurin** [comment]
Cool :+1:

**Pull request merged**
